### 1. Extracting Weather Data

In [8]:
import requests

In [9]:
url = "https://api.openweathermap.org/data/2.5/weather"

params = {
    "appid": "6a13e61e853763292101962a026aa3e8",
    "q": "Cairo"
}

response = requests.get(url, params=params)

data = response.json()

In [10]:
data

{'coord': {'lon': 31.2497, 'lat': 30.0626},
 'weather': [{'id': 800,
   'main': 'Clear',
   'description': 'clear sky',
   'icon': '01d'}],
 'base': 'stations',
 'main': {'temp': 295.57,
  'feels_like': 295.77,
  'temp_min': 295.05,
  'temp_max': 295.57,
  'pressure': 1013,
  'humidity': 73,
  'sea_level': 1013,
  'grnd_level': 1013},
 'visibility': 10000,
 'wind': {'speed': 1.54, 'deg': 90},
 'clouds': {'all': 0},
 'dt': 1790049403,
 'sys': {'type': 1,
  'id': 2514,
  'country': 'EG',
  'sunrise': 1790048588,
  'sunset': 1790092355},
 'timezone': 10800,
 'id': 360630,
 'name': 'Cairo',
 'cod': 200}

In [11]:
cities = [
    "Cairo",
    "Giza",
    "Alexandria",
    "Port Said",
    "Suez",
    "Ismailia",
    "Mansoura",
    "Tanta",
    "Luxor",
    "Aswan"
]

In [12]:
list_of_cities = []

In [13]:
for city in cities:
    print (city)
    url = "https://api.openweathermap.org/data/2.5/weather"
    params = {
    "appid": "6a13e61e853763292101962a026aa3e8",
    "q": city
  }

    response = requests.get(url, params=params)
    data = response.json()
    city = city 
    country = "Egypt"
    lat = data['coord']['lat']
    lon = data['coord']['lon']
    temp = data['main']['temp']
    pressure = data['main']['pressure']
    Humidity = data['main']['humidity']
    wind_speed = data['wind']['speed']
    WeatherMain = data['weather'][0]['main']
    WeatherDescription = data['weather'][0]['description']

    list_of_cities.append({
        'city': city,
        'country': country,
        'lat': lat,
        'lon': lon,
        'temp': temp,
        'pressure': pressure,
        'humidity': Humidity,
        'wind_speed': wind_speed , 
        'WeatherMain':WeatherMain ,
        'WeatherDescription' : WeatherDescription
    })

Cairo
Giza
Alexandria
Port Said
Suez
Ismailia
Mansoura
Tanta
Luxor
Aswan

In [14]:
list_of_cities

[{'city': 'Cairo',
  'country': 'Egypt',
  'lat': 30.0626,
  'lon': 31.2497,
  'temp': 295.57,
  'pressure': 1013,
  'humidity': 73,
  'wind_speed': 1.54,
  'WeatherMain': 'Clear',
  'WeatherDescription': 'clear sky'},
 {'city': 'Giza',
  'country': 'Egypt',
  'lat': 30.0081,
  'lon': 31.2109,
  'temp': 295.56,
  'pressure': 1013,
  'humidity': 77,
  'wind_speed': 0.19,
  'WeatherMain': 'Clear',
  'WeatherDescription': 'clear sky'},
 {'city': 'Alexandria',
  'country': 'Egypt',
  'lat': 31.2156,
  'lon': 29.9553,
  'temp': 294.13,
  'pressure': 1013,
  'humidity': 78,
  'wind_speed': 1.54,
  'WeatherMain': 'Clouds',
  'WeatherDescription': 'few clouds'},
 {'city': 'Port Said',
  'country': 'Egypt',
  'lat': 31.2565,
  'lon': 32.2841,
  'temp': 296.1,
  'pressure': 1013,
  'humidity': 85,
  'wind_speed': 4.24,
  'WeatherMain': 'Clouds',
  'WeatherDescription': 'scattered clouds'},
 {'city': 'Suez',
  'country': 'Egypt',
  'lat': 29.9737,
  'lon': 32.5263,
  'temp': 294.05,
  'pressure': 1013,
  'humidity': 83,
  'wind_speed': 1.77,
  'WeatherMain': 'Clear',
  'WeatherDescription': 'clear sky'},
 {'city': 'Ismailia',
  'country': 'Egypt',
  'lat': 30.6043,
  'lon': 32.2723,
  'temp': 293.81,
  'pressure': 1013,
  'humidity': 85,
  'wind_speed': 1.21,
  'WeatherMain': 'Clear',
  'WeatherDescription': 'clear sky'},
 {'city': 'Mansoura',
  'country': 'Egypt',
  'lat': 34.8616,
  'lon': -1.3394,
  'temp': 285.94,
  'pressure': 1021,
  'humidity': 82,
  'wind_speed': 0,
  'WeatherMain': 'Clear',
  'WeatherDescription': 'clear sky'},
 {'city': 'Tanta',
  'country': 'Egypt',
  'lat': 30.7885,
  'lon': 31.0019,
  'temp': 294.23,
  'pressure': 1013,
  'humidity': 80,
  'wind_speed': 1.71,
  'WeatherMain': 'Clear',
  'WeatherDescription': 'clear sky'},
 {'city': 'Luxor',
  'country': 'Egypt',
  'lat': 25.6989,
  'lon': 32.6421,
  'temp': 297.18,
  'pressure': 1011,
  'humidity': 53,
  'wind_speed': 1.03,
  'WeatherMain': 'Clear',
  'WeatherDescription': 'clear sky'},
 {'city': 'Aswan',
  'country': 'Egypt',
  'lat': 24.0934,
  'lon': 32.907,
  'temp': 298.76,
  'pressure': 1011,
  'humidity': 44,
  'wind_speed': 2.06,
  'WeatherMain': 'Clear',
  'WeatherDescription': 'clear sky'}]

### 2. Transformation

In [15]:
import pandas as pd

In [16]:
df = pd.DataFrame(list_of_cities)
df

,city,country,lat,lon,temp,pressure,humidity,wind_speed,WeatherMain,WeatherDescription
0,Cairo,Egypt,30.0626,31.2497,295.57,1013,73,1.54,Clear,clear sky
1,Giza,Egypt,30.0081,31.2109,295.56,1013,77,0.19,Clear,clear sky
2,Alexandria,Egypt,31.2156,29.9553,294.13,1013,78,1.54,Clouds,few clouds
3,Port Said,Egypt,31.2565,32.2841,296.10,1013,85,4.24,Clouds,scattered clouds
4,Suez,Egypt,29.9737,32.5263,294.05,1013,83,1.77,Clear,clear sky
5,Ismailia,Egypt,30.6043,32.2723,293.81,1013,85,1.21,Clear,clear sky
6,Mansoura,Egypt,34.8616,-1.3394,285.94,1021,82,0.00,Clear,clear sky
7,Tanta,Egypt,30.7885,31.0019,294.23,1013,80,1.71,Clear,clear sky
8,Luxor,Egypt,25.6989,32.6421,297.18,1011,53,1.03,Clear,clear sky
9,Aswan,Egypt,24.0934,32.9070,298.76,1011,44,2.06,Clear,clear sky

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   city                10 non-null     str
 1   country             10 non-null     str
 2   lat                 10 non-null     float64
 3   lon                 10 non-null     float64
 4   temp                10 non-null     float64
 5   pressure            10 non-null     int64
 6   humidity            10 non-null     int64
 7   wind_speed          10 non-null     float64
 8   WeatherMain         10 non-null     str
 9   WeatherDescription  10 non-null     str
dtypes: float64(4), int64(2), str(4)
memory usage: 1.2 KB

In [18]:
df['temp'] = df['temp']-273
df

,city,country,lat,lon,temp,pressure,humidity,wind_speed,WeatherMain,WeatherDescription
0,Cairo,Egypt,30.0626,31.2497,22.57,1013,73,1.54,Clear,clear sky
1,Giza,Egypt,30.0081,31.2109,22.56,1013,77,0.19,Clear,clear sky
2,Alexandria,Egypt,31.2156,29.9553,21.13,1013,78,1.54,Clouds,few clouds
3,Port Said,Egypt,31.2565,32.2841,23.10,1013,85,4.24,Clouds,scattered clouds
4,Suez,Egypt,29.9737,32.5263,21.05,1013,83,1.77,Clear,clear sky
5,Ismailia,Egypt,30.6043,32.2723,20.81,1013,85,1.21,Clear,clear sky
6,Mansoura,Egypt,34.8616,-1.3394,12.94,1021,82,0.00,Clear,clear sky
7,Tanta,Egypt,30.7885,31.0019,21.23,1013,80,1.71,Clear,clear sky
8,Luxor,Egypt,25.6989,32.6421,24.18,1011,53,1.03,Clear,clear sky
9,Aswan,Egypt,24.0934,32.9070,25.76,1011,44,2.06,Clear,clear sky

In [19]:
# Region Mapping
region_map = {
    "Cairo": "Greater Cairo",
    "Giza": "Greater Cairo",
    "Alexandria": "North Coast",
    "Port Said": "Canal",
    "Suez": "Canal",
    "Ismailia": "Canal",
    "Mansoura": "Lower Egypt",
    "Tanta": "Lower Egypt",
    "Luxor": "Upper Egypt",
    "Aswan": "Upper Egypt"
}

df["Region"] = df["city"].map(region_map)


# Temperature Category
def categorize_temperature(temp):
    if temp < 15:
        return "Cold"
    elif temp <= 25:
        return "Moderate"
    else:
        return "Hot"

df["TemperatureCategory"] = df["temp"].apply(categorize_temperature)


# Humidity Category
def categorize_humidity(humidity):
    if humidity < 40:
        return "Low"
    elif humidity <= 70:
        return "Medium"
    else:
        return "High"


df["HumidityCategory"] = df["humidity"].apply(categorize_humidity)

In [20]:
df

,city,country,lat,lon,temp,pressure,humidity,wind_speed,WeatherMain,WeatherDescription,Region,TemperatureCategory,HumidityCategory
0,Cairo,Egypt,30.0626,31.2497,22.57,1013,73,1.54,Clear,clear sky,Greater Cairo,Moderate,High
1,Giza,Egypt,30.0081,31.2109,22.56,1013,77,0.19,Clear,clear sky,Greater Cairo,Moderate,High
2,Alexandria,Egypt,31.2156,29.9553,21.13,1013,78,1.54,Clouds,few clouds,North Coast,Moderate,High
3,Port Said,Egypt,31.2565,32.2841,23.10,1013,85,4.24,Clouds,scattered clouds,Canal,Moderate,High
4,Suez,Egypt,29.9737,32.5263,21.05,1013,83,1.77,Clear,clear sky,Canal,Moderate,High
5,Ismailia,Egypt,30.6043,32.2723,20.81,1013,85,1.21,Clear,clear sky,Canal,Moderate,High
6,Mansoura,Egypt,34.8616,-1.3394,12.94,1021,82,0.00,Clear,clear sky,Lower Egypt,Cold,High
7,Tanta,Egypt,30.7885,31.0019,21.23,1013,80,1.71,Clear,clear sky,Lower Egypt,Moderate,High
8,Luxor,Egypt,25.6989,32.6421,24.18,1011,53,1.03,Clear,clear sky,Upper Egypt,Moderate,Medium
9,Aswan,Egypt,24.0934,32.9070,25.76,1011,44,2.06,Clear,clear sky,Upper Egypt,Hot,Medium

### 3. Load (Azure SQL Server)

In [21]:
import pyodbc

In [22]:
!pip install python-dotenv

Requirement already satisfied: python-dotenv in c:\users\anas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (1.2.3)

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: C:\Users\Anas\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [23]:
import os
from dotenv import load_dotenv

load_dotenv()

server = os.getenv("DB_SERVER")
database = os.getenv("DB_DATABASE")
username = os.getenv("DB_USERNAME")
password = os.getenv("DB_PASSWORD")

In [24]:
df

,city,country,lat,lon,temp,pressure,humidity,wind_speed,WeatherMain,WeatherDescription,Region,TemperatureCategory,HumidityCategory
0,Cairo,Egypt,30.0626,31.2497,22.57,1013,73,1.54,Clear,clear sky,Greater Cairo,Moderate,High
1,Giza,Egypt,30.0081,31.2109,22.56,1013,77,0.19,Clear,clear sky,Greater Cairo,Moderate,High
2,Alexandria,Egypt,31.2156,29.9553,21.13,1013,78,1.54,Clouds,few clouds,North Coast,Moderate,High
3,Port Said,Egypt,31.2565,32.2841,23.10,1013,85,4.24,Clouds,scattered clouds,Canal,Moderate,High
4,Suez,Egypt,29.9737,32.5263,21.05,1013,83,1.77,Clear,clear sky,Canal,Moderate,High
5,Ismailia,Egypt,30.6043,32.2723,20.81,1013,85,1.21,Clear,clear sky,Canal,Moderate,High
6,Mansoura,Egypt,34.8616,-1.3394,12.94,1021,82,0.00,Clear,clear sky,Lower Egypt,Cold,High
7,Tanta,Egypt,30.7885,31.0019,21.23,1013,80,1.71,Clear,clear sky,Lower Egypt,Moderate,High
8,Luxor,Egypt,25.6989,32.6421,24.18,1011,53,1.03,Clear,clear sky,Upper Egypt,Moderate,Medium
9,Aswan,Egypt,24.0934,32.9070,25.76,1011,44,2.06,Clear,clear sky,Upper Egypt,Hot,Medium

In [36]:
conn = pyodbc.connect(
    f"driver={{ODBC Driver 17 for SQL Server}};"
    f"server={server};"
    f"database={database};"
    f"UID={username};"
    f"PWD={password};"
)

cursor = conn.cursor()
cursor.execute("""
DROP TABLE IF EXISTS Anas_Ahmed_Task;

CREATE TABLE Anas_Ahmed_Task (
    city VARCHAR(50),
    country VARCHAR(50),
    lat FLOAT,
    lon FLOAT,
    temp FLOAT,
    pressure FLOAT,
    humidity FLOAT,
    wind_speed FLOAT,
    WeatherMain VARCHAR(50),
    WeatherDescription VARCHAR(100),
    Region VARCHAR(50),
    TemperatureCategory VARCHAR(50),
    HumidityCategory VARCHAR(50)
)
""")

conn.commit()

conn.commit()
cursor.close()
conn.close()

In [32]:
data = list(df.itertuples(index=False, name=None))

In [35]:
print(df.columns.tolist())
print(len(df.columns))

['city', 'country', 'lat', 'lon', 'temp', 'pressure', 'humidity', 'wind_speed', 'WeatherMain', 'WeatherDescription', 'Region', 'TemperatureCategory', 'HumidityCategory']
13

In [37]:
conn = pyodbc.connect(
    f"driver={{ODBC Driver 17 for SQL Server}};"
    f"server={server};"
    f"database={database};"
    f"UID={username};"
    f"PWD={password};"
)

cursor = conn.cursor()

data = list(df.itertuples(index=False, name=None))

cursor.executemany("""
    INSERT INTO Anas_Ahmed_Task
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
""", data)

conn.commit()

cursor.close()
conn.close()

In [38]:
conn = pyodbc.connect(
    f"driver={{ODBC Driver 17 for SQL Server}};"
    f"server={server};"
    f"database={database};"
    f"UID={username};"
    f"PWD={password};"
)

cursor = conn.cursor()

data = list(df.itertuples(index=False, name=None))

cursor.execute("""
    SELECT * FROM Anas_Ahmed_Task ;
""")
rows = cursor.fetchall()
conn.commit()
cursor.close()
conn.close()

In [39]:
print(rows)

[('Cairo', 'Egypt', 30.0626, 31.2497, 22.569999999999993, 1013.0, 73.0, 1.54, 'Clear', 'clear sky', 'Greater Cairo', 'Moderate', 'High'), ('Giza', 'Egypt', 30.0081, 31.2109, 22.560000000000002, 1013.0, 77.0, 0.19, 'Clear', 'clear sky', 'Greater Cairo', 'Moderate', 'High'), ('Alexandria', 'Egypt', 31.2156, 29.9553, 21.129999999999995, 1013.0, 78.0, 1.54, 'Clouds', 'few clouds', 'North Coast', 'Moderate', 'High'), ('Port Said', 'Egypt', 31.2565, 32.2841, 23.100000000000023, 1013.0, 85.0, 4.24, 'Clouds', 'scattered clouds', 'Canal', 'Moderate', 'High'), ('Suez', 'Egypt', 29.9737, 32.5263, 21.05000000000001, 1013.0, 83.0, 1.77, 'Clear', 'clear sky', 'Canal', 'Moderate', 'High'), ('Ismailia', 'Egypt', 30.6043, 32.2723, 20.810000000000002, 1013.0, 85.0, 1.21, 'Clear', 'clear sky', 'Canal', 'Moderate', 'High'), ('Mansoura', 'Egypt', 34.8616, -1.3394, 12.939999999999998, 1021.0, 82.0, 0.0, 'Clear', 'clear sky', 'Lower Egypt', 'Cold', 'High'), ('Tanta', 'Egypt', 30.7885, 31.0019, 21.230000000000018, 1013.0, 80.0, 1.71, 'Clear', 'clear sky', 'Lower Egypt', 'Moderate', 'High'), ('Luxor', 'Egypt', 25.6989, 32.6421, 24.180000000000007, 1011.0, 53.0, 1.03, 'Clear', 'clear sky', 'Upper Egypt', 'Moderate', 'Medium'), ('Aswan', 'Egypt', 24.0934, 32.907, 25.75999999999999, 1011.0, 44.0, 2.06, 'Clear', 'clear sky', 'Upper Egypt', 'Hot', 'Medium')]